**Case Study on Testing of Hypothesis**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/content/Sales_add.csv')

In [3]:
data

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402
5,Month-6,Region - A,Manager - B,137163,256948
6,Month-7,Region - C,Manager - C,130625,222106
7,Month-8,Region - A,Manager - A,131140,230637
8,Month-9,Region - B,Manager - C,171259,226261
9,Month-10,Region - C,Manager - B,141956,193735
10,Month-11,Region - B,Manager - C,159339,203175
11,Month-12,Region - A,Manager - A,178939,276279
12,Month-13,Region - B,Manager - A,145062,205180
13,Month-14,Region - A,Manager - A,151514,253131
14,Month-15,Region - C,Manager - A,147463,229336
15,Month-16,Region - A,Manager - B,177195,187305
16,Month-17,Region - A,Manager - C,140862,234908
17,Month-18,Region - C,Manager - B,167996,191517
18,Month-19,Region - B,Manager - A,132135,227040
19,Month-20,Region - A,Manager - B,152493,212579
20,Month-21,Region - B,Manager - A,147425,263388
21,Month-22,Region - A,Manager - C,130263,243020

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64
 4   Sales_After_digital_add(in $)   22 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes

In [5]:
data.describe()

       Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

**1. The company wishes to clarify whether there is any increase in sales after
stepping into digital marketing.**

**one-sample t-test on  difference in sales for each observation** #one method

Null Hypothesis (H0): There is no significant difference between the average increase in sales after the introduction of digital marketing and zero.

Alternative Hypothesis (H1): There is a significant increase in sales after the introduction of digital marketing.

In [24]:
from scipy.stats import ttest_1samp

sales_before_digital = data['Sales_before_digital_add(in $)']                           # Extract sales data before and after digital marketing
sales_after_digital = data['Sales_After_digital_add(in $)']

sales_differences = [after - before for before, after in zip(sales_before_digital, sales_after_digital)] # Calculate differences in sales

t_stat, p_value = ttest_1samp(sales_differences, 0)                                     # Perform one-sample t-test

print("One-Sample t-test results:")
print("t-statistic:", t_stat)                                                           # Output results
print("p-value:", p_value)
                                                                                        # Check significance
if p_value < 0.05:
    print("Reject the null hypothesis. There is a significant increase in average sales after the introduction of digital marketing.")
else:
    print("Fail to reject the null hypothesis. There is no significant increase in average sales after the introduction of digital marketing.")

One-Sample t-test results:
t-statistic: 12.09070525287017
p-value: 6.336667004575778e-11
Reject the null hypothesis. There is a significant increase in average sales after the introduction of digital marketing.

**Two-sample T-test**    #second method

Null Hypothesis (H0): There is no difference in average sales before and after the introduction of digital marketing.

Alternative Hypothesis (H1): There is a significant difference in average sales before and after the introduction of digital marketing.

In [21]:
from scipy.stats import ttest_rel

sales_before_digital = data['Sales_before_digital_add(in $)']        # Extract sales data before and after digital marketing
sales_after_digital = data['Sales_After_digital_add(in $)']

t_stat, p_value = ttest_rel(sales_after_digital,sales_before_digital)# Perform paired t-test

print("Paired t-test results:")                                      # Print the results
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < 0.05:                                                   # Check significance
    print("Reject the null hypothesis. There is a significant difference in average sales before and after digital marketing.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in average sales before and after digital marketing.")

Paired t-test results:
t-statistic: 12.09070525287017
p-value: 6.336667004575778e-11
Reject the null hypothesis. There is a significant difference in average sales before and after digital marketing.

**2. The company needs to check whether there is any dependency between
thefeatures “Region” and “Manager”.**

Null Hypothesis (H0): There is no association between the "Region" and "Manager" features.

Alternative Hypothesis (H1): There is an association between the "Region" and "Manager" features.

**chi-square test**

In [13]:
from scipy.stats import chi2_contingency

contingency_table = pd.crosstab(data['Region'], data['Manager'])       # Create a contingency table

chi2, p, dof, expected = chi2_contingency(contingency_table)           # Perform chi-square test

print("Chi-square Statistic:", chi2)                                   # Print results
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:")
print(expected)
                                                                       # Check significance
if p < 0.05:
    print("Reject the null hypothesis. There is a significant association between Region and Manager.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between Region and Manager.")

Chi-square Statistic: 3.050566893424036
p-value: 0.5493991051158094
Degrees of Freedom: 4
Expected Frequencies:
[[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Fail to reject the null hypothesis. There is no significant association between Region and Manager.